adds single quote string literal
ezylang/EvalEx pull request #416
Opened 2023-12-19 18:28 UTC by Snownee

This PR adds support for declaring a string literal using single quotes. This feature is disabled by default.

Related discussion: https://github.com/ezylang/EvalEx/discussions/383

2023-12-21 14:54 UTC, uklimaschewski requested changes
Thank yo very much, good idea in general.
But before I can merge his, please:
* Check and fix my code comments
* Extend the corresponding documentation with information on how to use string literals (chapters configuration and the STRING data type description).

2023-12-21 14:54 UTC, uklimaschewski commented on src/test/java/com/ezylang/evalex/parser/TokenizerStringLiteralTest.java
> +        .isInstanceOf(ParseException.class);
Avoid putting multiple tests into a single test method.
Extract this exception test to a separate exception test method, also check for the correct exception message.

2023-12-21 14:54 UTC, uklimaschewski commented on src/test/java/com/ezylang/evalex/parser/TokenizerStringLiteralTest.java
> +    assertAllTokensParsedCorrectly(
I would like to have more tests covering the behavior, if `singleQuoteStringLiteralsAllowed` is set to true:
- An equivalent of the `testErrorUnmatchedQuote...` tests here, using single quotes.
- Check if an escaped single quote is correctly parsed inside a single quote.
- Correct usage of single quotes inside double quotes and vice versa.

2023-12-23 10:03 UTC, uklimaschewski requested changes

2023-12-23 10:03 UTC, uklimaschewski commented on docs/configuration/configuration.md
> +### Single Quote String Literals
move this chapter above the "Strip Trailing Zeroes" chapter, the settings are sorted alphabetically.

2023-12-23 10:20 UTC, Snownee commented on docs/configuration/configuration.md
> +double quote character (") (default is false). If set to true, the expression will throw a _ParseException_.
Oops, it's a typo. Fixed now

2023-12-23 10:31 UTC, uklimaschewski approved these changes

2023-12-23 10:32 UTC, merged

2023-12-23 10:33 UTC, uklimaschewski commented
Thank you, I added some more clarification to the configuration documentation.