#435 Fix zero with scale to boolean (main)
ezylang/EvalEx pull request #437
Opened 2024-02-22 00:49 UTC by stevenylai

2024-02-22 09:02 UTC, Adler95 commented
@stevenylai I don't think this is the appropriate fix, as it doesn't really solve the: https://github.com/ezylang/EvalEx/issues/435.
The problem must be somewhere in the evaluation process since EvaluationValue already contains incorrect result.

2024-02-22 09:45 UTC, stevenylai commented
It's a follow-up for https://github.com/ezylang/EvalEx/issues/417 where the fix is to replace `.equals()` with `.compareTo()`. We missed the int -> boolean conversion part from the previous fix.

2024-02-22 10:34 UTC, Adler95 commented
All good. I agree with you that there is a necessity to replace .equals() with .compareTo(). I just wanted to point out that it doesn't fix the issues referenced in your PR comment. https://github.com/ezylang/EvalEx/issues/435 :)

2024-02-22 14:58 UTC, Adler95 commented
@stevenylai I just did a bit more detailed review of the process (at first I thought that this method is not invoked during evaluation). I can see now that this is the proper fix. I apologize for the false information and thank you for providing the fix quickly. :)

2024-02-24 10:38 UTC, uklimaschewski requested changes
Thanks, you were a little bit faster than me.
I have just one request: Can you not do the cast directly, but use the `getNumberValue()` method, instead?

2024-02-24 10:38 UTC, uklimaschewski commented on src/main/java/com/ezylang/evalex/data/EvaluationValue.java
> +        return ((BigDecimal) value).compareTo(BigDecimal.ZERO) != 0;
I'd do it a little bit cleaner:
`return getNumberValue().compareTo(BigDecimal.ZERO) != 0;`

`getNumberValue()`already does the cast.

2024-02-26 09:37 UTC, uklimaschewski approved these changes

2024-02-26 09:38 UTC, merged