Add STR_LENGTH, STR_MATCHES and STR_SUBSTRING
ezylang/EvalEx pull request #498
Opened 2024-09-09 17:49 UTC by HSGamer

Add some more functions for some common scenarios when working with Strings.

2024-09-15 11:04 UTC, uklimaschewski requested changes
Thank you very mich. Some little changes, then it is ok.

2024-09-15 11:04 UTC, uklimaschewski commented on src/main/java/com/ezylang/evalex/functions/string/StringSubstringFunction.java
> +      if (parameterValues[2].getNumberValue().intValue()
Merge this if statement with the enclosing one.

2024-09-16 15:06 UTC, HSGamer commented on docs/references/functions.md
> +| STR_SUBSTRING(string, start[, end]) | Returns a substring of the given string, starting at the _start_ index and ending at the _end_ index (the end of the string if not specified) |
Done

2024-09-16 15:20 UTC, uklimaschewski approved these changes

2024-09-16 15:21 UTC, merged